### ISSUE TITLE
Action fails with: sudo: a password is required

### ISSUE THREAD

**Issue by oerp-odoo** [hrishikesh-kadam/setup-lcov#4]
When I run like:

```yaml
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
```
I get this error:

```

Run $GITHUB_ACTION_PATH/src/install-lcov.sh \
  $GITHUB_ACTION_PATH/src/install-lcov.sh \
    
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SSH_AUTH_SOCK: /tmp/ssh-XXXXXXaPPtI6/agent.1115896
    SSH_AGENT_PID: 1115897
    pythonLocation: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64
    PKG_CONFIG_PATH: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64
    Python2_ROOT_DIR: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64
    Python3_ROOT_DIR: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64
    LD_LIBRARY_PATH: /opt/runner/actions-runner/_work/_tool/Python/3.10.12/x64/lib
    INPUT_PATH: src/versions/16.0/projects/demo/odoo.yml
    INPUT_BASE_PATH_SUBSTITUTES: /opt/odoo:src/versions/16.0/monodoo
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```
